/**
 * Websites the Scout reads for calls: funders, ministries, procurement portals, accelerators and development agencies worldwide.
 * Job boards, news sites and paid aggregators are left out on purpose. Reading is polite: robots.txt is respected and each site is visited about once a week.
 */
export const SITE_URLS: string[] = `
https://www.ungm.org/
https://www.un.org/
https://www.undp.org/
https://procurement-notices.undp.org/
https://www.unicef.org/supply/
https://www.unops.org/business-opportunities
https://www.wfp.org/procurement
https://www.fao.org/
https://www.who.int/about/accountability/procurement
https://www.unwomen.org/en/about-us/procurement
https://www.unido.org/get-involved/procurement
https://www.uncdf.org/procurement
https://www.unfpa.org/suppliers
https://www.unhcr.org/suppliers
https://www.unhabitat.org/
https://www.ilo.org/
https://www.itu.int/
https://www.ifad.org/
https://www.imo.org/
https://www.icao.int/
https://www.unep.org/
https://www.unesco.org/
https://www.worldbank.org/
https://projects.worldbank.org/
https://www.ifc.org/
https://www.miga.org/
https://www.afdb.org/
https://www.adb.org/
https://www.iadb.org/
https://www.ebrd.com/
https://www.isdb.org/
https://www.aiib.org/
https://www.eib.org/
https://www.caribank.org/
https://www.cdb.int/
https://www.gafspfund.org/
https://www.globalfund.org/
https://www.greenclimate.fund/
https://www.thegef.org/
https://www.adaptation-fund.org/
https://www.climateinvestmentfunds.org/
https://www.oecd.org/
https://www.developmentaid.org/
https://www.devex.com/
https://reliefweb.int/
https://www.dgmarket.com/
https://www.openopps.com/
https://bidanga.com/
https://www.opportunitydesk.org/
https://www.fundsforngos.org/
https://www.fundsforindividuals.com/
https://www.grants.gov/
https://www.sam.gov/
https://au.int/
https://au.int/en/opportunities
https://www.nepad.org/
https://www.africacdc.org/
https://www.afreximbank.com/
https://www.africafc.org/
https://www.africanriskcapacity.org/
https://www.comesa.int/
https://www.ecowas.int/
https://www.sadc.int/
https://www.eac.int/
https://igad.int/
https://www.cen-sad.org/
https://www.eccas.int/
https://www.uemoa.int/
https://www.africa50.com/
https://www.iita.org/
https://www.cgiar.org/
https://www.agra.org/
https://www.faraafrica.org/
https://www.asareca.org/
https://www.coraf.org/
https://www.fanrpan.org/
https://www.acts-net.org/
https://www.ppa.gov.gh/
https://www.ghaneps.gov.gh/
https://www.tenders.com.gh/
https://www.ghana.gov.gh/
https://www.mofep.gov.gh/
https://www.gea.gov.gh/
https://www.gipc.gov.gh/
https://www.moti.gov.gh/
https://www.mofa.gov.gh/
https://www.ndpc.gov.gh/
https://www.gsa.gov.gh/
https://www.csir.org.gh/
https://www.giz.de/en/worldwide/328.html
https://www.undp.org/ghana
https://www.worldbank.org/en/country/ghana
https://www.afdb.org/en/countries-and-regions/west-africa/ghana
https://www.mcc.gov/where-we-work/country/ghana
https://www.mastercardfdn.org/
https://www.kosmosinnovationcenter.com/
https://www.tonyelumelufoundation.org/
https://www.ghanachamber.org/
https://www.bpp.gov.ng/
https://nocopo.bpp.gov.ng/
https://egp.nigeria.gov.ng/
https://www.tenders.ng/
https://www.nigeriatenders.com/
https://www.boi.ng/
https://www.nepc.gov.ng/
https://smedan.gov.ng/
https://www.nipc.gov.ng/
https://www.undp.org/nigeria
https://www.worldbank.org/en/country/nigeria
https://www.afdb.org/en/countries-and-regions/west-africa/nigeria
https://www.ppra.go.ke/
https://tenders.go.ke/
https://ifmis.go.ke/
https://www.investkenya.go.ke/
https://www.kebs.org/
https://www.kalro.org/
https://www.undp.org/kenya
https://www.worldbank.org/en/country/kenya
https://www.etenders.gov.za/
https://www.treasury.gov.za/
https://secure.csd.gov.za/
https://www.cidb.org.za/
https://www.seda.org.za/
https://www.gov.za/
https://www.arc.agric.za/
https://www.idc.co.za/
https://www.ppra.go.tz/
https://www.taneps.go.tz/
https://www.tic.go.tz/
https://www.tanzania.go.tz/
https://www.costech.or.tz/
https://www.undp.org/tanzania
https://www.ppda.go.ug/
https://egpuganda.go.ug/
https://www.uia.go.ug/
https://www.uganda.go.ug/
https://www.mtic.go.ug/
https://www.naro.go.ug/
https://www.undp.org/uganda
https://www.rppa.gov.rw/
https://www.umucyo.gov.rw/
https://rdb.rw/
https://www.gov.rw/
https://www.rab.gov.rw/
https://www.bdf.rw/
https://www.zppa.org.zm/
https://eprocure.zppa.org.zm/
https://www.zda.org.zm/
https://www.gov.zm/
https://www.zari.gov.zm/
https://www.ppda.mw/
https://www.malawi.gov.mw/
https://www.mitc.mw/
https://www.mwapata.mw/
https://www.praz.org.zw/
https://www.gov.zw/
https://www.zimtrade.co.zw/
https://www.ppadb.co.bw/
https://www.gov.bw/
https://www.nda.gov.bw/
https://www.ceda.co.bw/
https://www.cp.gov.na/
https://www.gov.na/
https://www.nipdb.com/
https://www.gov.sz/
https://www.sedco.co.sz/
https://www.gov.ls/
https://www.lesotho.gov.ls/
https://www.marchespublics.gov.ma/
https://www.maroc.ma/
https://www.ada.gov.ma/
https://www.egp.gov.eg/
https://www.mof.gov.eg/
https://www.investinegypt.gov.eg/
https://www.tuneps.tn/
https://www.tunisia.gov.tn/
https://www.marches-publics.gov.dz/
https://www.andi.dz/
https://www.marchespublics.sn/
https://www.armp.sn/
https://www.gouv.sn/
https://www.marchespublics.ci/
https://www.gouv.ci/
https://www.publicprocurement.gov.sl/
https://www.gov.sl/
https://www.ppcc.gov.lr/
https://www.emansion.gov.lr/
https://gambia.gov.gm/
https://www.gppb.gm/
https://ec.europa.eu/info/funding-tenders/opportunities/portal/
https://commission.europa.eu/funding-tenders_en
https://ted.europa.eu/
https://eic.ec.europa.eu/
https://erasmus-plus.ec.europa.eu/
https://erc.europa.eu/
https://interreg.eu/
https://international-partnerships.ec.europa.eu/
https://www.eeas.europa.eu/
https://www.gov.uk/contracts-finder
https://www.find-tender.service.gov.uk/
https://www.gov.uk/government/organisations/foreign-commonwealth-development-office
https://fcdo.bravosolution.co.uk/
https://www.ukri.org/
https://www.ukri.org/opportunity/
https://www.gov.uk/apply-funding
https://www.innovateuk.ukri.org/
https://www.publiccontractsscotland.gov.uk/
https://www.sell2wales.gov.wales/
https://etendersni.gov.uk/
https://www.scottish-enterprise.com/
https://www.business.gov.uk/
https://www.enterprise-ireland.com/
https://www.boamp.fr/
https://www.marches-publics.gouv.fr/
https://www.france2030.gouv.fr/
https://www.bpifrance.fr/
https://www.afd.fr/
https://www.proparco.fr/
https://anr.fr/
https://www.evergabe-online.de/
https://www.dtvp.de/
https://www.foerderdatenbank.de/
https://www.kfw.de/
https://www.giz.de/
https://www.bafa.de/
https://www.bund.de/
https://www.bmbf.de/
https://www.dfg.de/
https://www.exist.de/
https://www.tenderned.nl/
https://www.pianoo.nl/
https://www.rvo.nl/
https://www.nwo.nl/
https://www.fmo.nl/
https://www.acquistinretepa.it/
https://www.anticorruzione.it/
https://www.invitalia.it/
https://contrataciondelestado.es/
https://www.cdti.es/
https://www.enisa.es/
https://www.aecid.es/
https://www.portugal2030.pt/
https://www.base.gov.pt/
https://www.iapmei.pt/
https://udbud.dk/
https://innovationsfonden.dk/
https://www.hankintailmoitukset.fi/
https://www.businessfinland.fi/
https://www.vinnova.se/
https://www.upphandlingsmyndigheten.se/
https://www.doffin.no/
https://www.innovasjonnorge.no/
https://www.simap.ch/
https://www.innosuisse.ch/
https://ezamowienia.gov.pl/
https://www.parp.gov.pl/
https://www.usp.gv.at/
https://www.ffg.at/
https://czechinvest.org/
https://riigihanked.riik.ee/
https://eis.ee/
https://cvpp.eviesiejipirkimai.lt/
https://inovacijuagentura.lt/
https://www.eis.gov.lv/
https://www.liaa.gov.lv/
https://www.cais.gov.bg/
https://eojn.nn.hr/
https://hamagbicro.hr/
https://ejn.gov.si/
https://www.guichet.lu/
https://www.etenders.gov.mt/
https://eprocure.gov.in/
https://gem.gov.in/
https://etenders.gov.in/
https://ireps.gov.in/
https://tenders.gov.in/
https://www.nabard.org/
https://www.sidbi.in/
https://www.startupindia.gov.in/
https://www.msme.gov.in/
https://www.icar.gov.in/
https://www.dst.gov.in/
https://www.birac.nic.in/
https://www.investindia.gov.in/
https://www.mof.go.jp/
https://www.e-gov.go.jp/
https://www.jetro.go.jp/
https://www.jica.go.jp/
https://www.nedo.go.jp/
https://www.koneps.go.kr/
https://www.g2b.go.kr/
https://www.k-startup.go.kr/
https://www.kotra.or.kr/
https://www.mss.go.kr/
https://www.gebiz.gov.sg/
https://www.business.gov.sg/
https://www.enterprisesg.gov.sg/
https://www.edb.gov.sg/
https://www.nrf.gov.sg/
https://myprocurement.gov.my/
https://www.mdec.my/
https://www.mida.gov.my/
https://www.smecorp.gov.my/
https://www.lkpp.go.id/
https://inaproc.id/
https://www.kemenkopukm.go.id/
https://www.bkpm.go.id/
https://www.e-gp.go.th/
https://www.nia.or.th/
https://www.nstda.or.th/
https://www.philgeps.gov.ph/
https://www.gov.ph/
https://www.dti.gov.ph/
https://www.dost.gov.ph/
https://muasamcong.mpi.gov.vn/
https://www.mpi.gov.vn/
https://www.vietnam.gov.vn/
https://www.eprocurement.gov.bd/
https://www.cptu.gov.bd/
https://www.bangladesh.gov.bd/
https://www.ppra.org.pk/
https://www.pakistan.gov.pk/
https://www.smeda.org.pk/
https://www.treasury.gov.lk/
https://www.gov.lk/
https://www.bolpatra.gov.np/
https://ppmo.gov.np/
https://www.gov.np/
https://www.gov.bt/
https://www.mof.gov.bt/
https://www.tender.gov.mn/
https://www.gov.mn/
https://www.investmongolia.gov.mn/
https://www.tenders.gov.au/
https://www.business.gov.au/
https://www.grants.gov.au/
https://www.industry.gov.au/
https://www.csiro.au/
https://www.austrade.gov.au/
https://www.gets.govt.nz/
https://www.business.govt.nz/
https://www.mbie.govt.nz/
https://www.mfat.govt.nz/
https://www.forumsec.org/
https://www.spc.int/
https://www.sprep.org/
https://www.pacifictradeinvest.com/
https://canadabuys.canada.ca/
https://www.canada.ca/en/services/business/grants.html
https://international.canada.ca/
https://www.idrc-crdi.ca/
https://grandchallenges.ca/
https://ised-isde.canada.ca/
https://www.merx.com/
https://www.comprasnet.gov.br/
https://www.gov.br/compras/
https://www.bndes.gov.br/
https://compranet.hacienda.gob.mx/
https://www.gob.mx/
https://www.chilecompra.cl/
https://www.mercadopublico.cl/
https://www.colombiacompra.gov.co/
https://www.contratos.gov.co/
https://www.argentina.gob.ar/comprar
https://comprar.gob.ar/
https://www.gob.pe/osce
https://www.sercop.gob.ec/
https://www.compraspublicas.gob.ec/
https://www.contrataciones.gov.py/
https://www.dncp.gov.py/
https://www.comprasestatales.gub.uy/
https://www.sicop.go.cr/
https://www.panamacompra.gob.pa/
https://www.dgcp.gob.do/
https://www.comprasdominicana.gov.do/
https://etimad.sa/
https://www.mof.gov.sa/
https://www.my.gov.sa/
https://mof.gov.ae/
https://esupply.dubai.gov.ae/
https://u.ae/
https://www.tenderboard.gov.bh/
https://www.bahrain.bh/
https://monaqasat.mof.gov.qa/
https://www.gov.qa/
https://www.pta.gov.om/
https://www.omantender.com/
https://www.joneps.gov.jo/
https://www.jordan.gov.jo/
https://mr.gov.il/
https://www.gov.il/
https://www.israelinnovation.org.il/
https://www.investsaudi.sa/
https://www.misa.gov.sa/
https://www.gatesfoundation.org/
https://www.rockefellerfoundation.org/
https://www.fordfoundation.org/
https://www.macfound.org/
https://www.hewlett.org/
https://www.mellon.org/
https://www.opensocietyfoundations.org/
https://www.wkkf.org/
https://www.skoll.org/
https://www.omidyar.com/
https://www.ashoka.org/
https://www.awdf.org/
https://www.globalfundforwomen.org/
https://www.womenwin.org/
https://www.womenforwomen.org/
https://www.cherieblairfoundation.org/
https://www.youthcolab.org/
https://www.globalyouthmobilization.org/
https://www.commonwealthyouth.org/
https://www.youthbusiness.org/
https://www.iyfnet.org/
https://www.agcofoundation.org/
https://www.syngentafoundation.org/
https://www.climate-kic.org/
https://climate-launchpad.org/
https://www.climatepolicyinitiative.org/
https://www.climateworks.org/
https://www.conservation.org/
https://www.gca.org/
https://www.f6s.com/
https://www.techstars.com/
https://www.antler.co/
https://www.masschallenge.org/
https://solve.mit.edu/
https://www.orange.com/en/orange-corners
https://vc4a.com/
https://www.africarena.com/
https://www.seedstars.com/
https://www.flat6labs.com/
https://www.mestafrica.com/
https://www.villagecapital.com/
https://www.endeavor.org/
https://www.startupbootcamp.org/
https://research-and-innovation.ec.europa.eu/
https://wellcome.org/
https://www.nrf.ac.za/
https://www.dst.gov.za/
https://www.csir.org/
https://www.acdivoca.org/
https://www.technoserve.org/
https://www.heifer.org/
https://www.cabi.org/
https://www.fcdoservices.gov.uk/
https://www.sida.se/
https://www.norad.no/
https://www.danida.dk/
https://www.koica.go.kr/
https://www.eda.admin.ch/
https://www.sdc.admin.ch/
https://www.bmz.de/
https://www.aics.gov.it/
https://www.youthop.com/
https://www.opportunitiesforafricans.com/
https://www.africanopportunities.com/
https://www.globalgiving.org/
https://www.entrepreneurship.org/
`.trim().split('\n');
