-- Ghana districts (level 2 of geo_units): 261 Metropolitan, Municipal and District Assemblies, grouped under their regions.
-- Source: Districts of Ghana (Wikipedia), as it stood after the Guan District was inaugurated in October 2021. Verify against the Local Government Service list before relying on it for reporting.
-- Safe to re-run: existing rows are skipped.
INSERT INTO "geo_units" ("country_code","level","parent_id","name","source")
SELECT 'GH', 2, r."id", d."name", 'Districts of Ghana, Wikipedia (261 MMDAs, as at October 2021). Verify against the Local Government Service list.'
FROM (VALUES
('Ahafo','Asunafo North Municipal'),
('Ahafo','Asunafo South District'),
('Ahafo','Asutifi North District'),
('Ahafo','Asutifi South District'),
('Ahafo','Tano North Municipal'),
('Ahafo','Tano South Municipal'),
('Ashanti','Adansi Asokwa District'),
('Ashanti','Adansi North District'),
('Ashanti','Adansi South District'),
('Ashanti','Afigya-Kwabre North District'),
('Ashanti','Afigya-Kwabre South District'),
('Ashanti','Ahafo-Ano North Municipal'),
('Ashanti','Ahafo-Ano South East District'),
('Ashanti','Ahafo-Ano South West District'),
('Ashanti','Akrofuom District'),
('Ashanti','Amansie Central District'),
('Ashanti','Amansie West District'),
('Ashanti','Amansie South District'),
('Ashanti','Asante-Akim Central Municipal'),
('Ashanti','Asante-Akim North District'),
('Ashanti','Asante-Akim South Municipal'),
('Ashanti','Asokore-Mampong Municipal'),
('Ashanti','Asokwa Municipal'),
('Ashanti','Atwima-Kwanwoma District'),
('Ashanti','Atwima-Mponua District'),
('Ashanti','Atwima-Nwabiagya Municipal'),
('Ashanti','Atwima-Nwabiagya North District'),
('Ashanti','Bekwai Municipal'),
('Ashanti','Bosome Freho District'),
('Ashanti','Bosomtwe District'),
('Ashanti','Ejisu Municipal'),
('Ashanti','Ejura/Sekyedumase Municipal'),
('Ashanti','Juaben Municipal'),
('Ashanti','Kumasi Metropolitan'),
('Ashanti','Kwabre East Municipal'),
('Ashanti','Kwadaso Municipal'),
('Ashanti','Mampong Municipal'),
('Ashanti','Obuasi East Municipal'),
('Ashanti','Obuasi Municipal'),
('Ashanti','Offinso Municipal'),
('Ashanti','Offinso North District'),
('Ashanti','Oforikrom Municipal'),
('Ashanti','Old Tafo Municipal'),
('Ashanti','Sekyere Afram Plains District'),
('Ashanti','Sekyere Central District'),
('Ashanti','Sekyere East District'),
('Ashanti','Sekyere Kumawu District'),
('Ashanti','Sekyere South District'),
('Ashanti','Suame Municipal'),
('Bono','Banda District'),
('Bono','Berekum East Municipal'),
('Bono','Berekum West District'),
('Bono','Dormaa Central Municipal'),
('Bono','Dormaa East District'),
('Bono','Dormaa West District'),
('Bono','Jaman North District'),
('Bono','Jaman South Municipal'),
('Bono','Sunyani Municipal'),
('Bono','Sunyani West District'),
('Bono','Tain District'),
('Bono','Wenchi Municipal'),
('Bono East','Atebubu-Amantin Municipal'),
('Bono East','Kintampo North Municipal'),
('Bono East','Kintampo South District'),
('Bono East','Nkoranza North District'),
('Bono East','Nkoranza South Municipal'),
('Bono East','Pru East District'),
('Bono East','Pru West District'),
('Bono East','Sene East District'),
('Bono East','Sene West District'),
('Bono East','Techiman Municipal'),
('Bono East','Techiman North District'),
('Central','Abura/Asebu/Kwamankese District'),
('Central','Agona East District'),
('Central','Agona West Municipal'),
('Central','Ajumako/Enyan/Essiam District'),
('Central','Asikuma Odoben Brakwa District'),
('Central','Assin Central Municipal'),
('Central','Assin North District'),
('Central','Assin South District'),
('Central','Awutu Senya East Municipal'),
('Central','Awutu Senya West District'),
('Central','Cape Coast Metropolitan'),
('Central','Effutu Municipal'),
('Central','Ekumfi District'),
('Central','Gomoa East District'),
('Central','Gomoa Central District'),
('Central','Gomoa West District'),
('Central','Komenda/Edina/Eguafo/Abirem Municipal'),
('Central','Mfantsiman Municipal'),
('Central','Twifo Atti Morkwa District'),
('Central','Twifo/Hemang/Lower Denkyira District'),
('Central','Upper Denkyira East Municipal'),
('Central','Upper Denkyira West District'),
('Eastern','Abuakwa North Municipal'),
('Eastern','Abuakwa South Municipal'),
('Eastern','Achiase District'),
('Eastern','Akuapim North Municipal'),
('Eastern','Akuapim South District'),
('Eastern','Akyemansa District'),
('Eastern','Asene Manso Akroso District'),
('Eastern','Asuogyaman District'),
('Eastern','Atiwa East District'),
('Eastern','Atiwa West District'),
('Eastern','Ayensuano District'),
('Eastern','Birim Central Municipal'),
('Eastern','Birim North District'),
('Eastern','Birim South District'),
('Eastern','Denkyembour District'),
('Eastern','Fanteakwa North District'),
('Eastern','Fanteakwa South District'),
('Eastern','Kwaebibirem Municipal'),
('Eastern','Kwahu Afram Plains North District'),
('Eastern','Kwahu Afram Plains South District'),
('Eastern','Kwahu East District'),
('Eastern','Kwahu South District'),
('Eastern','Kwahu West Municipal'),
('Eastern','Lower Manya Krobo Municipal'),
('Eastern','New Juaben North Municipal'),
('Eastern','New Juaben South Municipal'),
('Eastern','Nsawam Adoagyire Municipal'),
('Eastern','Okere District'),
('Eastern','Suhum Municipal'),
('Eastern','Upper Manya Krobo District'),
('Eastern','Upper West Akim District'),
('Eastern','West Akim Municipal'),
('Eastern','Yilo-Krobo Municipal'),
('Greater Accra','Ablekuma Central Municipal'),
('Greater Accra','Ablekuma North Municipal'),
('Greater Accra','Ablekuma West Municipal'),
('Greater Accra','Accra Metropolitan'),
('Greater Accra','Ada East District'),
('Greater Accra','Ada West District'),
('Greater Accra','Adenta Municipal'),
('Greater Accra','Ashaiman Municipal'),
('Greater Accra','Ayawaso Central Municipal'),
('Greater Accra','Ayawaso East Municipal'),
('Greater Accra','Ayawaso North Municipal'),
('Greater Accra','Ayawaso West Municipal'),
('Greater Accra','Ga Central Municipal'),
('Greater Accra','Ga East Municipal'),
('Greater Accra','Ga North Municipal'),
('Greater Accra','Ga South Municipal'),
('Greater Accra','Ga West Municipal'),
('Greater Accra','Korle-Klottey Municipal'),
('Greater Accra','Kpone-Katamanso Municipal'),
('Greater Accra','Krowor Municipal'),
('Greater Accra','La-Dade-Kotopon Municipal'),
('Greater Accra','La-Nkwantanang-Madina Municipal'),
('Greater Accra','Ledzokuku Municipal'),
('Greater Accra','Ningo-Prampram District'),
('Greater Accra','Okaikwei North Municipal'),
('Greater Accra','Shai-Osudoku District'),
('Greater Accra','Tema Metropolitan'),
('Greater Accra','Tema West Municipal'),
('Greater Accra','Weija Gbawe Municipal'),
('Northern','Gushegu Municipal'),
('Northern','Karaga District'),
('Northern','Kpandai District'),
('Northern','Kumbungu District'),
('Northern','Mion District'),
('Northern','Nanton District'),
('Northern','Nanumba North Municipal'),
('Northern','Nanumba South District'),
('Northern','Saboba District'),
('Northern','Sagnarigu Municipal'),
('Northern','Savelugu Municipal'),
('Northern','Tamale Metropolitan'),
('Northern','Tatale Sanguli District'),
('Northern','Tolon District'),
('Northern','Yendi Municipal'),
('Northern','Zabzugu District'),
('North East','Bunkpurugu Nyankpanduri District'),
('North East','Chereponi District'),
('North East','East Mamprusi Municipal'),
('North East','Mamprugu Moagduri District'),
('North East','West Mamprusi Municipal'),
('North East','Yunyoo-Nasuan District'),
('Oti','Biakoye District'),
('Oti','Guan District'),
('Oti','Jasikan Municipal'),
('Oti','Kadjebi District'),
('Oti','Krachi East Municipal'),
('Oti','Krachi Nchumuru District'),
('Oti','Krachi West Municipal'),
('Oti','Nkwanta North District'),
('Oti','Nkwanta South Municipal'),
('Savannah','Bole District'),
('Savannah','Central Gonja District'),
('Savannah','East Gonja Municipal'),
('Savannah','North Gonja District'),
('Savannah','North East Gonja District'),
('Savannah','Sawla-Tuna-Kalba District'),
('Savannah','West Gonja Municipal'),
('Upper East','Bawku Municipal'),
('Upper East','Bawku West District'),
('Upper East','Binduri District'),
('Upper East','Bolgatanga East District'),
('Upper East','Bolgatanga Municipal'),
('Upper East','Bongo District'),
('Upper East','Builsa North Municipal'),
('Upper East','Builsa South District'),
('Upper East','Garu District'),
('Upper East','Kassena-Nankana Municipal'),
('Upper East','Kassena-Nankana West District'),
('Upper East','Nabdam District'),
('Upper East','Pusiga District'),
('Upper East','Talensi District'),
('Upper East','Tempane District'),
('Upper West','Daffiama Bussie Issa District'),
('Upper West','Jirapa Municipal'),
('Upper West','Lambussie Karni District'),
('Upper West','Lawra Municipal'),
('Upper West','Nadowli-Kaleo District'),
('Upper West','Nandom Municipal'),
('Upper West','Sissala East Municipal'),
('Upper West','Sissala West District'),
('Upper West','Wa East District'),
('Upper West','Wa Municipal'),
('Upper West','Wa West District'),
('Volta','Adaklu District'),
('Volta','Afadzato South District'),
('Volta','Agotime Ziope District'),
('Volta','Akatsi North District'),
('Volta','Akatsi South District'),
('Volta','Anloga District'),
('Volta','Central Tongu District'),
('Volta','Ho Municipal'),
('Volta','Ho West District'),
('Volta','Hohoe Municipal'),
('Volta','Keta Municipal'),
('Volta','Ketu North Municipal'),
('Volta','Ketu South Municipal'),
('Volta','Kpando Municipal'),
('Volta','North Dayi District'),
('Volta','North Tongu District'),
('Volta','South Dayi District'),
('Volta','South Tongu District'),
('Western','Ahanta West Municipal'),
('Western','Amenfi Central District'),
('Western','Amenfi West Municipal'),
('Western','Effia Kwesimintsim Municipal'),
('Western','Ellembelle District'),
('Western','Jomoro Municipal'),
('Western','Mpohor District'),
('Western','Nzema East Municipal'),
('Western','Prestea-Huni Valley Municipal'),
('Western','Sekondi Takoradi Metropolitan'),
('Western','Shama District'),
('Western','Tarkwa-Nsuaem Municipal'),
('Western','Wassa Amenfi East Municipal'),
('Western','Wassa East District'),
('Western North','Aowin Municipal'),
('Western North','Bia East District'),
('Western North','Bia West District'),
('Western North','Bibiani Anhwiaso Bekwai Municipal'),
('Western North','Bodi District'),
('Western North','Juaboso District'),
('Western North','Sefwi Akontombra District'),
('Western North','Sefwi-Wiawso Municipal'),
('Western North','Suaman District')
) AS d("region","name")
JOIN "geo_units" r ON r."country_code" = 'GH' AND r."level" = 1 AND r."name" = d."region"
ON CONFLICT DO NOTHING;
