-- Consent notices, Ghana, version 1. Wording approved by Amin Yahaya on 2026-10-03. Loaded as Draft; publishing needs an approver and legal review.
-- Safe to re-run: existing versions are never overwritten.
INSERT INTO consent_notices (purpose, country_code, version, text, status) VALUES
('account', 'GH', 1, 'Create my Samakose account. I agree that Samakose Integrated Development Organisation may use my name, email address and organisation name to create and run my account, to send me messages about my account, and to keep a security record of when I sign in. I understand my account is checked by Samakose before I can use all features. I can close my account at any time.', 'Draft'),
('assessment', 'GH', 1, 'Use my role and business details to prepare my assessment. I agree that Samakose may use my job role, the way I plan to answer the assessment, and my business details (sector, size, location, years operating) to decide which questions to show me first and to prepare my business health assessment. These answers help route questions to the right person. They do not decide my score. A Samakose expert reviews every official score.', 'Draft'),
('team_invites', 'GH', 1, 'Let me invite colleagues to answer parts of the assessment. I agree that Samakose may send an invitation email to the colleagues I name, and share with each of them only the questions I assign to them. I confirm that I have told them I am inviting them. They can see only their own questions, never my score or other sections.', 'Draft'),
('demographics', 'GH', 1, 'Help show who Samakose reaches (optional). I agree that Samakose may keep my gender and age band, so that it can show donors and partners, in totals only, how many women-led and youth-led businesses it supports. This never changes my score, my report or the support I receive. I can skip this, and I can remove my answers at any time.', 'Draft'),
('disability', 'GH', 1, 'Tell Samakose about a disability (optional). Disability is sensitive information, so I am asking separately. I agree that Samakose may keep whether I, or my business''s owner, live with a disability. It is used only to count, in totals, how inclusive the support is, and to make sure services are accessible. It is never used in my score, my diagnosis or any decision about me. Only the business owner and the Samakose Administrator can see my own answer. Totals with fewer than five people are never shown. I can say "I prefer not to say", and I can remove my answer at any time.', 'Draft'),
('funder_aggregate', 'GH', 1, 'Include my business in anonymous totals. I agree that Samakose may include my business''s results in combined totals for donors, investors and development partners, such as how many businesses improved. No business is named, and a group of fewer than five is never reported. I can withdraw at any time. If I withdraw, my business is left out of future totals but cannot be removed from totals already published.', 'Draft')
ON CONFLICT (purpose, country_code, version) DO NOTHING;
