import './auth';
import './work';
import './platform';
import './network';
import './unlock';
import './delivery';
import './indicators';
import './programme-finance';
import './programme-workspaces';
import './cohort-configurations';
export { routes } from '../framework';
