import './auth';
import './work';
import './platform';
import './network';
import './unlock';
import './delivery';
import './indicators';
import './programme-finance';
import './programme-workspaces';
import './cohort-configurations';
import './delivery-operations';
import './delivery-coordination';
import './programme-calendar';
import './provider-assignments';
export { routes } from '../framework';