import * as cert from '@/services/certificates';
import { z } from 'zod';
import { badRequest } from '@/lib/errors';
import { defineRoute, status } from '../framework';
import { listQuery } from '../list';
import { caseState, email, evidenceClass, isoDate, name, optText, orgType, text, uuid, empty } from '../schemas';
import * as orgs from '@/services/orgs';
import * as progs from '@/services/programmes';
import * as cases from '@/services/cases';
import * as asg from '@/services/assignments';
import * as diag from '@/services/diagnostics';
import * as record from '@/services/record';
import * as ev from '@/services/evidence';
import * as clin from '@/services/clinical';
import * as del from '@/services/delivery';
import * as rep from '@/services/reports';
import { exportReport } from '@/services/report-export';

/* ---------------------------- organisations ---------------------------- */
const O = 'Organisations';
const orgBody = z.object({ name, type: orgType.optional(), sector: optText(), region: optText(), district: optText(), size: optText(40), contactName: optText(), contactEmail: z.union([z.literal(''), z.string().trim().email('Enter a valid email').max(200)]).nullish().transform((v) => (v === undefined ? undefined : v || null)), contactPhone: optText(40) });
defineRoute({ method: 'GET', path: '/organisations', tag: O, summary: 'List organisations in your scope', permission: ['organisations', 'read'], query: listQuery.extend({ region: z.string().optional(), type: z.string().optional(), status: z.string().optional() }), handler: ({ ctx, query }) => orgs.listOrgs(ctx, query) });
defineRoute({ method: 'POST', path: '/organisations', tag: O, summary: 'Register an organisation with recorded consent', permission: ['organisations', 'create'], body: orgBody.extend({ consent: z.boolean(), consentBy: name }), handler: async ({ ctx, body }) => status(201, await orgs.createOrg(ctx, body as any)) });
defineRoute({ method: 'GET', path: '/organisations/:id', tag: O, summary: 'One organisation with its cases', permission: ['organisations', 'read'], handler: ({ ctx, params }) => orgs.getOrg(ctx, params.id) });
defineRoute({ method: 'GET', path: '/organisations/:id/record', tag: O, summary: 'Business Health Record: the organisation history across cases, scores with reasons for change, and framework versions', permission: ['scores', 'read'], handler: ({ ctx, params }) => record.healthRecord(ctx, params.id) });
defineRoute({ method: 'PATCH', path: '/organisations/:id', tag: O, summary: 'Update an organisation', permission: ['organisations', 'edit'], body: orgBody.partial().extend({ status: z.enum(['Active', 'Inactive']).optional() }), handler: ({ ctx, params, body }) => orgs.updateOrg(ctx, params.id, body as any) });
defineRoute({ method: 'DELETE', path: '/organisations/:id', tag: O, summary: 'Archive an organisation (kept for the audit trail)', permission: ['organisations', 'delete'], handler: ({ ctx, params }) => orgs.archiveOrg(ctx, params.id) });

/* ------------------------------ programmes ----------------------------- */
const P = 'Programmes';
const progBody = z.object({ name, funder: optText(), startDate: isoDate.nullish(), endDate: isoDate.nullish(), budgetGhs: z.number().min(0).max(1e10).nullish() });
defineRoute({ method: 'GET', path: '/programmes', tag: P, summary: 'List programmes', permission: ['programmes', 'read'], query: listQuery.extend({ status: z.string().optional() }), handler: ({ ctx, query }) => progs.listProgrammes(ctx, query) });
defineRoute({ method: 'POST', path: '/programmes', tag: P, summary: 'Create a programme', permission: ['programmes', 'create'], body: progBody, handler: async ({ ctx, body }) => status(201, await progs.createProgramme(ctx, body as any)) });
defineRoute({ method: 'GET', path: '/programmes/:id', tag: P, summary: 'One programme with cohorts', permission: ['programmes', 'read'], handler: ({ ctx, params }) => progs.getProgramme(ctx, params.id) });
defineRoute({ method: 'PATCH', path: '/programmes/:id', tag: P, summary: 'Update a programme or move its status', permission: ['programmes', 'edit'], body: progBody.partial().extend({ status: z.enum(['Draft', 'Active', 'Completed', 'Cancelled']).optional() }), handler: ({ ctx, params, body }) => progs.updateProgramme(ctx, params.id, body as any) });
defineRoute({ method: 'POST', path: '/programmes/:id/cohorts', tag: P, summary: 'Add a cohort', permission: ['cohorts', 'create'], body: z.object({ name, startDate: isoDate.nullish(), endDate: isoDate.nullish(), capacity: z.number().int().min(1).max(5000) }), handler: async ({ ctx, params, body }) => status(201, await progs.createCohort(ctx, params.id, body as any)) });
defineRoute({ method: 'PATCH', path: '/cohorts/:id', tag: P, summary: 'Update a cohort', permission: ['cohorts', 'edit'], body: z.object({ name: name.optional(), startDate: isoDate.nullish(), endDate: isoDate.nullish(), capacity: z.number().int().min(1).max(5000).optional(), status: z.enum(['Draft', 'Open', 'Closed']).optional() }), handler: ({ ctx, params, body }) => progs.updateCohort(ctx, params.id, body as any) });

/* -------------------------------- cases -------------------------------- */
const C = 'Cases';
defineRoute({ method: 'GET', path: '/cases', tag: C, summary: 'List cases in your scope', permission: ['cases', 'read'], query: listQuery.extend({ status: z.string().optional(), programmeId: z.string().optional(), cohortId: z.string().optional(), consultantId: z.string().optional() }), handler: ({ ctx, query }) => cases.listCases(ctx, query) });
defineRoute({ method: 'POST', path: '/cases', tag: C, summary: 'Open a case for an organisation', permission: ['cases', 'create'], body: z.object({ orgId: uuid, programmeId: uuid.nullish(), cohortId: uuid.nullish(), startState: z.enum(['PROSPECT', 'ONBOARDING', 'PROFILED']).optional() }), handler: async ({ ctx, body }) => status(201, await cases.createCase(ctx, body)) });
defineRoute({ method: 'GET', path: '/cases/:id', tag: C, summary: 'Case summary with facts and next steps', permission: ['cases', 'read'], handler: ({ ctx, params }) => cases.getCase(ctx, params.id) });
defineRoute({ method: 'POST', path: '/cases/:id/assign', tag: C, summary: 'Assign lead expert, coaching expert and reviewer', permission: ['cases', 'assign'], body: z.object({ consultantId: uuid.nullish(), coachId: uuid.nullish(), reviewerId: uuid.nullish(), reason: z.string().max(500).nullish() }), handler: ({ ctx, params, body }) => asg.assignCase(ctx, params.id, body) });
defineRoute({ method: 'POST', path: '/cases/:id/transition', tag: C, summary: 'Confirm a manual state change', permission: ['cases', 'edit'], body: z.object({ to: caseState, reason: optText(500) }), handler: ({ ctx, params, body }) => cases.transitionCase(ctx, params.id, body.to, body.reason ?? undefined) });
defineRoute({ method: 'GET', path: '/cases/:id/activity', tag: C, summary: 'Activity feed for a case', permission: ['cases', 'read'], handler: ({ ctx, params }) => cases.caseActivity(ctx, params.id) });

/* ------------------------- diagnostic, evidence ------------------------ */
const D = 'Diagnostic and evidence';
const answers = z.record(z.string().regex(/^[A-Z0-9][A-Z0-9_-]{1,15}$/), z.union([z.number(), z.object({ value: z.number().optional(), notApplicable: z.boolean().optional(), evidence: evidenceClass.optional(), ref: z.string().max(40).nullish(), note: z.string().max(500).nullish() })]));
defineRoute({ method: 'GET', path: '/questions', tag: D, summary: 'Questions of the current published framework version (for the given case when caseId is sent)', permission: ['diagnostics', 'read'], query: z.object({ caseId: z.string().uuid().optional() }), handler: ({ ctx, query }) => diag.activeQuestions(ctx, query.caseId) });
defineRoute({ method: 'POST', path: '/cases/:id/diagnostics/validate', tag: D, summary: 'Check answers against the data quality gate without saving', permission: ['diagnostics', 'create'], body: z.object({ answers }), handler: ({ ctx, params, body }) => diag.preflight(ctx, params.id, body.answers as any) });
defineRoute({ method: 'POST', path: '/cases/:id/diagnostics', tag: D, summary: 'Submit a diagnostic. It is validated and scored at once.', permission: ['diagnostics', 'create'], body: z.object({ answers, uuid: z.string().max(80).optional() }), handler: async ({ ctx, params, body }) => status(201, await diag.submitDiagnostic(ctx, params.id, body as any)) });
defineRoute({ method: 'GET', path: '/cases/:id/diagnostics', tag: D, summary: 'Diagnostic submissions for a case', permission: ['diagnostics', 'read'], handler: ({ ctx, params }) => diag.listDiagnostics(ctx, params.id) });
defineRoute({ method: 'GET', path: '/cases/:id/certification', tag: D, summary: 'Certificate status, eligibility criteria and history', permission: ['cases', 'read'], handler: ({ ctx, params }) => cert.certification(ctx, params.id) });
defineRoute({ method: 'POST', path: '/cases/:id/certification/propose', tag: D, summary: 'Propose a business health certificate (lead expert or administrator)', permission: ['cases', 'edit'], body: z.object({ rationale: z.string().trim().min(10).max(800) }), handler: async ({ ctx, params, body }) => status(201, await cert.propose(ctx, params.id, body.rationale)) });
defineRoute({ method: 'POST', path: '/certificates/:id/decision', tag: D, summary: 'Certify or decline a proposal. Must be a different person from the proposer', permission: ['cases', 'certify'], body: z.object({ decision: z.enum(['Certify', 'Decline']), note: z.string().trim().min(5).max(600) }), handler: ({ ctx, params, body }) => cert.decide(ctx, params.id, body) });
defineRoute({ method: 'POST', path: '/certificates/:id/verification', tag: D, summary: 'Owner agrees, or stops agreeing, that the certificate can be confirmed from its link', permission: ['cases', 'read'], body: z.object({ on: z.boolean() }), handler: ({ ctx, params, body }) => cert.setVerification(ctx, params.id, body.on) });
defineRoute({ method: 'GET', path: '/cases/:id/investment-pack', tag: D, summary: 'Investment readiness summary for a valid Investment-ready certificate', permission: ['cases', 'read'], handler: ({ ctx, params }) => cert.investmentPack(ctx, params.id) });
defineRoute({ method: 'POST', path: '/certificates/:id/revoke', tag: D, summary: 'Revoke a certificate, with a reason', permission: ['cases', 'certify'], body: z.object({ reason: z.string().trim().min(5).max(600) }), handler: ({ ctx, params, body }) => cert.revoke(ctx, params.id, body.reason) });
defineRoute({ method: 'GET', path: '/cases/:id/scores', tag: D, summary: 'Score history and latest breakdown', permission: ['scores', 'read'], handler: ({ ctx, params }) => diag.caseScores(ctx, params.id) });
defineRoute({ method: 'POST', path: '/cases/:id/rescore', tag: D, summary: 'Score again from the current evidence', permission: ['evidence', 'edit'], body: empty, handler: ({ ctx, params }) => diag.rescore(ctx, params.id) });
defineRoute({ method: 'GET', path: '/cases/:id/evidence', tag: D, summary: 'Evidence items for a case', permission: ['evidence', 'read'], handler: ({ ctx, params }) => ev.listEvidence(ctx, params.id) });
defineRoute({ method: 'POST', path: '/cases/:id/evidence', tag: D, summary: 'Add an evidence item', permission: ['evidence', 'create'], body: z.object({ description: text(3, 500), class: evidenceClass.optional(), documentId: uuid.nullish(), link: z.string().max(500).nullish() }), handler: async ({ ctx, params, body }) => status(201, await ev.addEvidence(ctx, params.id, body as any)) });
defineRoute({ method: 'PATCH', path: '/evidence/:id', tag: D, summary: 'Verify or reclassify evidence. The score is recalculated.', permission: ['evidence', 'edit'], body: z.object({ class: evidenceClass.optional(), description: text(3, 500).optional() }), handler: ({ ctx, params, body }) => ev.updateEvidence(ctx, params.id, body) });
defineRoute({ method: 'POST', path: '/documents', tag: D, summary: 'Upload a document (multipart: file, caseId or orgId)', permission: ['documents', 'create'], multipart: true, handler: async ({ ctx, req }) => { let form: FormData; try { form = await req.formData(); } catch { throw badRequest('Send the file as multipart form data'); } return status(201, await ev.uploadDocument(ctx, form)); } });
defineRoute({ method: 'GET', path: '/documents', tag: D, summary: 'List documents for a case or organisation', permission: ['documents', 'read'], query: z.object({ caseId: z.string().optional(), orgId: z.string().optional() }), handler: ({ ctx, query }) => ev.listDocuments(ctx, query) });
defineRoute({ method: 'GET', path: '/documents/:id/download', tag: D, summary: 'Download a document (checked against its fingerprint)', permission: ['documents', 'read'], handler: ({ ctx, params }) => ev.downloadDocument(ctx, params.id) });

/* --------------------- diagnosis, prescription, review ------------------ */
const R = 'Diagnosis and prescription';
const dgnBody = z.object({ summary: text(20, 4000), rootCauses: z.array(z.object({ cause: text(3, 500), evidence_ids: z.array(z.string()).min(1) })).min(1).max(10), priority: z.enum(['High', 'Medium', 'Low']), risks: z.array(z.object({ text: text(3, 500), severity: z.enum(['High', 'Medium', 'Low']) })).max(20) });
const items = z.array(z.object({ library_id: z.string(), actions: z.array(z.object({ text: text(3, 500), owner_role: z.enum(['OWNER', 'COACH', 'CONSULTANT']), deadline_days: z.number().int() })).min(1).max(10), kpi_ids: z.array(z.string()).optional() })).min(1).max(12);
defineRoute({ method: 'POST', path: '/cases/:id/diagnoses/generate', tag: R, summary: 'Ask AI to draft a diagnosis (runs in the background)', permission: ['diagnoses', 'create'], body: empty, handler: ({ ctx, params }) => clin.requestDiagnosis(ctx, params.id) });
defineRoute({ method: 'GET', path: '/cases/:id/diagnoses', tag: R, summary: 'Diagnosis versions for a case', permission: ['diagnoses', 'read'], handler: ({ ctx, params }) => clin.listDiagnoses(ctx, params.id) });
defineRoute({ method: 'POST', path: '/cases/:id/diagnoses', tag: R, summary: 'Write a diagnosis by hand', permission: ['diagnoses', 'create'], body: dgnBody, handler: async ({ ctx, params, body }) => status(201, await clin.createDiagnosis(ctx, params.id, body)) });
defineRoute({ method: 'POST', path: '/diagnoses/:id/revise', tag: R, summary: 'Save an edited diagnosis as a new version', permission: ['diagnoses', 'edit'], body: dgnBody, handler: async ({ ctx, params, body }) => status(201, await clin.reviseDiagnosis(ctx, params.id, body)) });
defineRoute({ method: 'POST', path: '/diagnoses/:id/review', tag: R, summary: 'Accept or reject a diagnosis', permission: ['diagnoses', 'edit'], body: z.object({ decision: z.enum(['Reviewed', 'Rejected']), note: optText(1000) }), handler: ({ ctx, params, body }) => clin.reviewDiagnosis(ctx, params.id, { decision: body.decision, note: body.note ?? undefined }) });
defineRoute({ method: 'POST', path: '/cases/:id/prescriptions/generate', tag: R, summary: 'Ask AI to draft a prescription from the approved library', permission: ['prescriptions', 'create'], body: empty, handler: ({ ctx, params }) => clin.requestPrescription(ctx, params.id) });
defineRoute({ method: 'GET', path: '/cases/:id/prescriptions', tag: R, summary: 'Prescription versions for a case', permission: ['prescriptions', 'read'], handler: ({ ctx, params }) => clin.listPrescriptions(ctx, params.id) });
defineRoute({ method: 'POST', path: '/cases/:id/prescriptions', tag: R, summary: 'Write a prescription by hand', permission: ['prescriptions', 'create'], body: z.object({ items }), handler: async ({ ctx, params, body }) => status(201, await clin.createPrescription(ctx, params.id, body.items as any)) });
defineRoute({ method: 'POST', path: '/prescriptions/:id/revise', tag: R, summary: 'Save an edited prescription as a new version', permission: ['prescriptions', 'edit'], body: z.object({ items }), handler: async ({ ctx, params, body }) => status(201, await clin.revisePrescription(ctx, params.id, body.items as any)) });
defineRoute({ method: 'POST', path: '/prescriptions/:id/submit', tag: R, summary: 'Send a prescription to the reviewer', permission: ['prescriptions', 'edit'], body: empty, handler: ({ ctx, params }) => clin.submitPrescription(ctx, params.id) });
defineRoute({ method: 'POST', path: '/prescriptions/:id/review', tag: R, summary: 'Approve or return a prescription (reviewer only)', permission: ['prescriptions', 'approve'], body: z.object({ decision: z.enum(['APPROVED', 'RETURNED']), reason: optText(1000) }), handler: ({ ctx, params, body }) => clin.reviewPrescription(ctx, params.id, { decision: body.decision, reason: body.reason ?? undefined }) });
defineRoute({ method: 'GET', path: '/reviews/queue', tag: R, summary: 'Work waiting for review or rework', permission: ['prescriptions', 'read'], handler: ({ ctx }) => clin.reviewQueue(ctx) });

/* ------------------- actions, risks, KPIs, coaching, reports ------------ */
const A = 'Delivery';
defineRoute({ method: 'GET', path: '/actions', tag: A, summary: 'List actions (mine, overdue, by case)', permission: ['actions', 'read'], query: listQuery.extend({ caseId: z.string().optional(), status: z.string().optional(), assigneeId: z.string().optional(), overdue: z.string().optional(), mine: z.string().optional(), horizon: z.string().optional() }), handler: ({ ctx, query }) => del.listActions(ctx, query) });
defineRoute({ method: 'POST', path: '/cases/:id/actions', tag: A, summary: 'Add an action to a case', permission: ['actions', 'create'], body: z.object({ text: text(3, 500), ownerRole: z.enum(['OWNER', 'COACH', 'CONSULTANT']), dueDate: isoDate, assigneeId: uuid.nullish() }), handler: async ({ ctx, params, body }) => status(201, await del.createAction(ctx, params.id, body)) });
defineRoute({ method: 'PATCH', path: '/actions/:id', tag: A, summary: 'Update status, evidence note, assignee or due date', permission: ['actions', 'edit'], body: z.object({ status: z.enum(['Open', 'In progress', 'Done']).optional(), evidenceNote: text(1, 1000).optional(), assigneeId: uuid.nullish(), dueDate: isoDate.optional() }), handler: ({ ctx, params, body }) => del.updateAction(ctx, params.id, body) });
defineRoute({ method: 'GET', path: '/cases/:id/risks', tag: A, summary: 'Risks flagged on a case', permission: ['risks', 'read'], handler: ({ ctx, params }) => del.listRisks(ctx, params.id) });
defineRoute({ method: 'POST', path: '/cases/:id/risks', tag: A, summary: 'Record a risk', permission: ['risks', 'edit'], body: z.object({ text: text(3, 500), severity: z.enum(['High', 'Medium', 'Low']) }), handler: async ({ ctx, params, body }) => status(201, await del.createRisk(ctx, params.id, body)) });
defineRoute({ method: 'PATCH', path: '/risks/:id', tag: A, summary: 'Update a risk', permission: ['risks', 'edit'], body: z.object({ status: z.enum(['Open', 'Mitigating', 'Accepted', 'Closed']).optional(), severity: z.enum(['High', 'Medium', 'Low']).optional(), text: text(3, 500).optional() }), handler: ({ ctx, params, body }) => del.updateRisk(ctx, params.id, body) });
defineRoute({ method: 'GET', path: '/cases/:id/kpis', tag: A, summary: 'Indicators with readings and progress', permission: ['kpis', 'read'], handler: ({ ctx, params }) => del.listKpis(ctx, params.id) });
defineRoute({ method: 'POST', path: '/cases/:id/kpis', tag: A, summary: 'Add an indicator', permission: ['kpis', 'create'], body: z.object({ name: text(2, 120), unit: optText(30), baseline: z.number().nullish(), target: z.number().nullish() }), handler: async ({ ctx, params, body }) => status(201, await del.createKpi(ctx, params.id, body)) });
defineRoute({ method: 'PATCH', path: '/kpis/:id', tag: A, summary: 'Update an indicator', permission: ['kpis', 'edit'], body: z.object({ name: text(2, 120).optional(), unit: optText(30), baseline: z.number().nullish(), target: z.number().nullish() }), handler: ({ ctx, params, body }) => del.updateKpi(ctx, params.id, body) });
defineRoute({ method: 'POST', path: '/kpis/:id/readings', tag: A, summary: 'Record a reading (readings are never edited)', permission: ['kpis', 'create'], body: z.object({ value: z.number().min(-1e9).max(1e9), readingDate: isoDate, sourceClass: evidenceClass.optional() }), handler: async ({ ctx, params, body }) => status(201, await del.addReading(ctx, params.id, body)) });
defineRoute({ method: 'GET', path: '/sessions', tag: A, summary: 'Coaching sessions', permission: ['sessions', 'read'], query: z.object({ caseId: z.string().optional(), upcoming: z.string().optional() }), handler: ({ ctx, query }) => del.listSessions(ctx, query) });
defineRoute({ method: 'POST', path: '/cases/:id/sessions', tag: A, summary: 'Schedule a coaching session', permission: ['sessions', 'create'], body: z.object({ scheduledAt: z.string().datetime({ offset: true }) }), handler: async ({ ctx, params, body }) => status(201, await del.createSession(ctx, params.id, body)) });
defineRoute({ method: 'PATCH', path: '/sessions/:id', tag: A, summary: 'Record the outcome of a session or move it', permission: ['sessions', 'edit'], body: z.object({ status: z.enum(['Held', 'Missed', 'Cancelled']).optional(), notes: z.string().max(4000).optional(), scheduledAt: z.string().datetime({ offset: true }).optional() }), handler: ({ ctx, params, body }) => del.updateSession(ctx, params.id, body) });
defineRoute({ method: 'POST', path: '/sessions/:id/brief', tag: A, summary: 'Prepare a coaching brief (background)', permission: ['sessions', 'edit'], body: empty, handler: ({ ctx, params }) => del.requestBrief(ctx, params.id) });

const RP = 'Reports';
defineRoute({ method: 'POST', path: '/cases/:id/reports/generate', tag: RP, summary: 'Draft a progress report (background)', permission: ['reports', 'create'], body: empty, handler: ({ ctx, params }) => rep.requestReport(ctx, params.id) });
defineRoute({ method: 'GET', path: '/cases/:id/reports', tag: RP, summary: 'Reports for a case', permission: ['reports', 'read'], handler: ({ ctx, params }) => rep.listReports(ctx, params.id) });
defineRoute({ method: 'GET', path: '/reports/:id', tag: RP, summary: 'One report', permission: ['reports', 'read'], handler: ({ ctx, params }) => rep.getReport(ctx, params.id) });
defineRoute({ method: 'PATCH', path: '/reports/:id', tag: RP, summary: 'Edit a draft report', permission: ['reports', 'create'], body: z.object({ title: text(3, 200).optional(), content: z.array(z.object({ heading: text(1, 200), body: text(1, 6000) })).min(1).max(20).optional() }), handler: ({ ctx, params, body }) => rep.editReport(ctx, params.id, body) });
defineRoute({ method: 'GET', path: '/reports/:id/export', tag: RP, summary: 'Download a released report as Word or PDF', permission: ['reports', 'read'], query: z.object({ format: z.enum(['docx', 'pdf']).default('pdf') }), handler: ({ ctx, params, query }) => exportReport(ctx, params.id, (query as { format: 'docx' | 'pdf' }).format) });
defineRoute({ method: 'POST', path: '/reports/:id/release', tag: RP, summary: 'Release a report to the owner (reviewer only)', permission: ['reports', 'approve'], body: empty, handler: ({ ctx, params }) => rep.releaseReport(ctx, params.id, 'release') });
defineRoute({ method: 'POST', path: '/reports/:id/return', tag: RP, summary: 'Send a report back to the author', permission: ['reports', 'approve'], body: z.object({ reason: text(5, 1000) }), handler: ({ ctx, params, body }) => rep.releaseReport(ctx, params.id, 'return', body.reason) });
export { email };
